### PR TITLE
Make entire project a python package and installable with pip

### PR DESCRIPTION
**Pull request by timmeinhardt**
I suggest to move all Python files except from `train.py` and `enjoy.py` to a Python package subdirectory which is installable via the additional `setup.py`. While this does not yet register the package as an official PyPI package, it allows to execute:
```
pip3 install https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/archive/master.zip
```
and then write an individual training script. While this makes the entire project more maintainable it also facilitates the integration into individual projects.

### CODE REVIEW

**Comment by ikostrikov** [comment]
I'm sorry that it takes so long to review the PR, I'm currently on an internship so I have much less free time.

**Comment by Omegastick** [comment]
I'm using this branch (merged into the master branch of the main repo, so as to get the newer updates) and it works fine. It'd be really nice to have this merged into the main repo too.

**Comment by timmeinhardt** [comment]
You can also install my branch directly by executing:
`pip3 install https://github.com/timmeinhardt/pytorch-a2c-ppo-acktr/archive/pipify_to_installable_package.zip`

**Comment by ikostrikov** [comment]
I think I'm ready to merge it. Does it require any commits or it's ready?

**Comment by timmeinhardt** [comment]
From my side this ready to be merged!

**Comment by ikostrikov** [comment]
Merged. Can you also add a line to readme?

**Pull request merged**
